---
title: "Constitute data base of journalists"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidytext)
library(dplyr)
library(tidyr)
library(stopwords)
library(ggplot2)
library(stringi)
library(Dict)
library(Xplortext)
library(DescTools)
library(stringr)
library(FactoMineR)
```

```{r}
library(rtweet)
auth <- rtweet_app()
# access_token <- "AAAAAAAAAAAAAAAAAAAAAIcKLwEAAAAA9Ve0dVTIyaecdx0XwYfOpoLYQek%3D9g08wPfTo0IQSPu16Ysj0aYpXkr11ETwzN9ZFhNcvCx3lC5RQl"
```

```{r}
redactions <- Dict$new(
  LeMonde = c("@LeMonde", "Le Monde", "@lemondefr", "le monde", "#LeMonde", "@lemonde_pol", "#lemonde", "@decodeurs", "lemonde"),
  LeFig = c("@Le_Figaro", "@FigaroVox", "@Figaro", "Figaro", "FigaroVox", "#Figaro", "@Figaro_culture"),
  Libe = c("@libe", "@Libe", "Libé", "Libération", "Liberation", "liberation"),
  Mediapart = c("Mediapart", "@Mediapart", "Médiapart", "@mediapart", "@MediapartBlogs", "mediapart"),
  Point = c("@LePoint", "Le Point", "Le point", "Point"),
  Valeur = c("@Valeurs", "VA", "@VAplus_", "Valeurs actuelles"),
  Obs = c("@lobs", "L'Obs", "Le nouvel observateur", "lenouvelobservateur"),
  Marianne = c("@Marianne_TVoff", "@MarianneleMag", "Marianne"),
  AFP = c("AFP", "@afpfr", "Agence France-Presse"),
  Blast = c("@blast_france", "Blast", "BLAST"),
  Cnews = c("@CNEWS", "@CNews", "Cnews", "CNEWS", "@cnews"),
  Express = c("@LEXPRESS", "L'Express", "Express", "l'express"),
  Inter = c("France Inter", "@franceinter", "@franceinfo", "Inter"),
  Europe = c("@Europe1", "Europe 1", "europe1", "#Europe1"),
  BFM = c("BFM", "@BFMTV", "BFMTV", "@bfmtv"),
  Lacroix = c("@LaCroix", "LaCroix", "La Croix", "la croix"),
  Parisien = c("@le_Parisien", "Le Parisien", "le parisien"),
  LaProvence = c("La Provence", "@laprovence", "@LaProvence", "#laprovence", "#LaProvence"),
  OuestFrance = c("@OuestFrance", "Ouest-France", "ouest-france"),
  VoixDuNord = c("@lavoixdunord", "lavoixdunord.fr", "La Voix du Nord", "La Voix Du Nord", "la voix du nord", "Voix du Nord"),
  LeProgres = c("@Le_Progres", "Le Progrès", "Le Progres", "Le progres", "leprogres.fr"),
  SudOuest = c("Sud Ouest", "@SO_Paysbasque", "#SO_Paysbasque", "sudouest.fr"),
  DauphineLibere = c("@ledauphine", "#dauphinelibere", "Le Dauphiné Libéré", "Le Dauphiné", "Dauphiné Libéré"),
  EstRep = c("@lestrepublicain", "L'Est Républicain", "@LEstRepNancy"))
```

Load the previous batches.

```{r}
load("../data/journalist-and-description.RData")
total <- probable.journalist
rm(probable.journalist)
```

Take the subset of journalist for which we have at least one redaction.

```{r}
has.redactions <- rep(0, nrow(total))

for (redac in redactions$keys){
  has.redactions <- has.redactions + total[, redac]
}

total$has.redactions <- has.redactions

hist(total$has.redactions)
```

```{r}
total <- total[total$has.redactions > 0,]
```


```{r}
# initialisation
timeline <- get_timeline("LeaSalame", n = 10, lang = "fr", include_rts = FALSE)
timeline$screen_name <- rep("LeaSalame", nrow(timeline))
```


```{r}
count = 0
store = 10 
# filling the table
for (name in total$screen_name[3002:3010]){
  
  if (count < 501){
    
      count = count + 1
      print(paste0("doing ", name))
      try(new_row <- get_timeline(name, n = 1000, lang = "fr", include_rts = FALSE), silent = TRUE)
      new_row$screen_name <- rep(name, nrow(new_row))
      timeline <- rbind(timeline, new_row)
  
  } else {
      
      date_time <- Sys.time()
      print(paste0("starting the break at ", date_time))
      
      new.name <- paste0("../data/timeline", store, ".Rdata")
      save(timeline, file = new.name)
      store = store + 1
      timeline <- timeline[1,]
      
      # start the nap!
      Sys.sleep(16*60)  
      date_time <- Sys.time()
      print(paste0("ending the break at ", date_time))
      
      count = 0
  }
}
```


```{r}
save(timeline, file = "../data/timeline2800-3000-short.RData") 
```

