---
title: "Constitute data base of journalists"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidytext)
library(dplyr)
library(tidyr)
library(stopwords)
library(ggplot2)
library(stringi)
library(Dict)
library(Xplortext)
library(DescTools)
library(stringr)
library(FactoMineR)
```

```{r}
library(rtweet)
#readRenviron("~/.Renviron")

auth <- rtweet_app()
# access_token <- "AAAAAAAAAAAAAAAAAAAAAIcKLwEAAAAA9Ve0dVTIyaecdx0XwYfOpoLYQek%3D9g08wPfTo0IQSPu16Ysj0aYpXkr11ETwzN9ZFhNcvCx3lC5RQl"
```

```{r}
redactions <- Dict$new(
  LeMonde = c("@LeMonde", "Le Monde", "@lemondefr", "le monde", "#LeMonde", "@lemonde_pol", "#lemonde", "@decodeurs"),
  LeFig = c("@Le_Figaro", "@FigaroVox", "@Figaro", "Figaro", "FigaroVox", "#Figaro"),
  Libe = c("@libe", "@Libe", "Libé", "Libération", "Liberation", "liberation"),
  Mediapart = c("Mediapart", "@Mediapart", "Médiapart", "@mediapart", "@MediapartBlogs", "mediapart"),
  Point = c("@LePoint", "Le Point", "Le point", "Point"),
  Valeur = c("@Valeurs", "VA", "@VAplus_", "Valeurs actuelles"),
  Obs = c("@lobs", "L'Obs", "Le nouvel observateur", "lenouvelobservateur"),
  Marianne = c("@Marianne_TVoff", "@MarianneleMag", "Marianne"),
  AFP = c("AFP", "@afpfr", "Agence France-Presse"),
  Blast = c("@blast_france", "Blast", "BLAST"),
  Cnews = c("@CNEWS", "@CNews", "Cnews", "CNEWS", "@cnews"),
  Express = c("@LEXPRESS", "L'Express", "Express", "l'express"),
  Inter = c("France Inter", "@franceinter", "@franceinfo", "Inter"),
  Europe = c("@Europe1", "Europe 1", "europe1", "#Europe1"),
  BFM = c("BFM", "@BFMTV", "BFMTV", "@bfmtv"),
  Lacroix = c("@LaCroix", "LaCroix", "La Croix", "la croix"),
  Parisien = c("@le_Parisien", "Le Parisien", "le parisien"),
  LaProvence = c("La Provence", "@laprovence", "@LaProvence", "#laprovence", "#LaProvence"),
  OuestFrance = c("@OuestFrance", "Ouest-France", "ouest-france"),
  VoixDuNord = c("@lavoixdunord", "lavoixdunord.fr", "La Voix du Nord", "La Voix Du Nord", "la voix du nord", "Voix du Nord"),
  LeProgres = c("@Le_Progres", "Le Progrès", "Le Progres", "Le progres", "leprogres.fr"),
  SudOuest = c("Sud Ouest", "@SO_Paysbasque", "#SO_Paysbasque", "sudouest.fr"),
  DauphineLibere = c("@ledauphine", "#dauphinelibere", "Le Dauphiné Libéré", "Le Dauphiné", "Dauphiné Libéré"),
  EstRep = c("@lestrepublicain", "L'Est Républicain", "@LEstRepNancy"))
```

Load the previous batches

```{r}
load("./batch4.Rdata")
total <- probable.journalist
# load("./batch2.Rdata")
# total <- rbind(total, probable.journalist)
# load("./batch3.Rdata")
# total <- rbind(total, probable.journalist)
# load("./batch4.Rdata")
# total <- rbind(total, probable.journalist)
# rm(probable.journalist)
```

Take the subset of journalist for which we have at least one redaction.

```{r}
has.redactions <- rep(0, nrow(total))

for (redac in redactions$keys){
  has.redactions <- has.redactions + total[, redac]
}

total$has.redactions <- has.redactions

hist(total$has.redactions)
```

```{r}
total <- total[total$has.redactions > 0,]
```


```{r}
# initialisation
timeline <- get_timeline("LeaSalame", n = 1, lang = "fr", include_rts = FALSE)

# filling the table
for (name in total$screen_name){
  new_row <- get_timeline(name, n = 1000, lang = "fr", include_rts = FALSE)
  timeline <- rbind(timeline, new_row)
}
```

Add year column for each of 

```{r}
timeline$year <- stri_sub(timeline$created_at, -4)
timeline$month <- stri_sub(timeline$created_at, from = 4, to = 7)
timeline$day <- stri_sub(timeline$created_at, from = 1, to = 3)
```

Keep only relevant columns 

```{r}
timeline <- timeline[, c("created_at", "id", "full_text", "is_quote_status", "favorite_count", "retweet_count", "lang", "retweeted", "possibly_sensitive", "year", "month", "day")]
```


```{r}
# delete urls
timeline$treated.text <- gsub("http[^[:space:]]*", "", timeline$full_text)

# delete words or tag referring to the newspapper
for (redaction in redactions$keys){
  for (tag in redaction){
    timeline$treated.text <- gsub(tag, "", timeline$treated.text)
  }
}
```


```{r}
resTD <- TextData(timeline[timeline$lang == "fr",], var.text = c(13), idiom="fr", lminword=3, Fmin=8, Dmin=4, stop.word.tm=TRUE, stop.word.user=c("amp","7h40","et"), context.quali=c("year"))
summary(resTD,ndoc=0,nword=10)
```


