redactions <- Dict$new(
  LeMonde = c("@LeMonde", "Le Monde", "@lemondefr", "le monde", "#LeMonde", "@lemonde_pol", "#lemonde", "@decodeurs", "Monde", "lemonde"),
  LeFigaro = c("@Le_Figaro", "@FigaroVox", "@Figaro", "Figaro", "FigaroVox", "#Figaro"),
  Libe = c("@libe", "@Libe", "Libé", "Libération", "Liberation", "liberation"),
  LesEchos = c("@LesEchos", "LesEchos", "@LesEchosWeekEnd", "LesEchosWeekEnd", "Les Échos", "Les Echos", "LesÉchos"),
  Mediapart = c("Mediapart", "@Mediapart", "Médiapart", "@mediapart", "@MediapartBlogs", "mediapart"),
  Point = c("@LePoint", "Le Point", "Le point", "Point"),
  LOpinion = c("@lopinion_fr", "l'Opinion", "l'opinion", "LOpinion", "lopinion", "lopinion_fr"),
  JDD = c("leJDD", "le JDD", "JDD", "#JDD", "Le JDD", "Journal du Dimanche", "journal du dimanche"),
  LaTribune = c("LaTribune", "@LaTribune", "La Tribune", "latribune"),
  Atlantico = c("atlantico_fr", "@atlantico_fr", "Atlantico", "atlantico.fr", "#Atlantico"),
  Valeur = c("@Valeurs", "VA", "@VAplus_", "Valeurs actuelles"),
  LHumanite = c("humanite_fr", "@humanite_fr", "L'Humanité", "L'Huma", "l'huma", "humanite.fr", "l'Humanite", "l'Huma"),
  Obs = c("@lobs", "L'Obs", "Le nouvel observateur", "lenouvelobservateur"),
  Marianne = c("@Marianne_TVoff", "@MarianneleMag", "Marianne"),
  AFP = c("AFP", "@afpfr", "Agence France-Presse"),
  Blast = c("@blast_france", "Blast", "BLAST"),
  Cnews = c("@CNEWS", "@CNews", "Cnews", "CNEWS", "@cnews"),
  Express = c("@LEXPRESS", "L'Express", "Express", "l'express"),
  Inter = c("France Inter", "@franceinter", "@franceinfo", "Inter"),
  Europe = c("@Europe1", "Europe 1", "europe1", "#Europe1"),
  BFM = c("BFM", "@BFMTV", "BFMTV", "@bfmtv"),
  Lacroix = c("@LaCroix", "LaCroix", "La Croix", "la croix"),
  Parisien = c("@le_Parisien", "Le Parisien", "le parisien"),
  LaProvence = c("La Provence", "@laprovence", "@LaProvence", "#laprovence", "#LaProvence"),
  OuestFrance = c("@OuestFrance", "Ouest-France", "ouest-france"),
  VoixDuNord = c("@lavoixdunord", "lavoixdunord.fr", "La Voix du Nord", "La Voix Du Nord", "la voix du nord", "Voix du Nord"),
  LeProgres = c("@Le_Progres", "Le Progrès", "Le Progres", "Le progres", "leprogres.fr"),
  SudOuest = c("Sud Ouest", "@SO_Paysbasque", "#SO_Paysbasque", "sudouest.fr"),
  DauphineLibere = c("@ledauphine", "#dauphinelibere", "Le Dauphiné Libéré", "Le Dauphiné", "Dauphiné Libéré"),
  EstRep = c("@lestrepublicain", "L'Est Républicain", "@LEstRepNancy"),
  RTL = c("@RTLFrance", "@RTLSoir", "RTL", "#RTL"),
  RMC = c("rmcinfo", "@RMCStorytv", "RMCInfo"),
  SudRadio = c("SudRadio", "@SudRadio", "Sud Radio", "sud radio", "#SudRadio", "SudRadio"),
  FranceCulture = c("franceculture", "France Culture", "FC_actu", "Rédaction de France Culture", "@franceculture"),
  Arte = c("ARTEfr", "ARTE"),
  France5 = c("@France5tv", "France5tv", "#France5", "cavousf5", "@cavousf5", "#CàVous"),
  TF1 = c("@TF1", "TF1", "#TF1", "#LesMatinsLCI", "LCI", "tf1", "@tf1"),
  C8 = c("C8", "C8TV", "@C8TV", "@TPMP", "TPMP"),
  France2 = c("@france2tv", "@QuelleEpoqueOff", "France2tv", "#France2"),
  France3 = c("France3tv", "#France3"),
  M6 = c("@M6", "M6", "#M6", "#ZoneInterdite"),
  ArretSurImages = c("arretsurimages", "@arretsurimages", "Arrêt sur images", "arrêt sur images", "arretsurimages.net"))



